//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaChica
    {
        public long IdUsuario { get; set; }
        public short IdSucursal { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal MONTO { get; set; }
        public bool Estado { get; set; }
        public int IDCajaChica { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
