//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversionesProductos
    {
        public int IdConversion { get; set; }
        public long IdProductoSAP { get; set; }
        public Nullable<long> IdProductoDestino { get; set; }
        public Nullable<double> Cantidad { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Productos Productos1 { get; set; }
    }
}
