//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePluAdquirido
    {
        public int IdDetalle { get; set; }
        public long IdProducto { get; set; }
        public double Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public int IdDetalleFactura { get; set; }
    
        public virtual DetalleFactura DetalleFactura { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
