//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaE()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
        }
    
        public string Nit { get; set; }
        public System.DateTime FechaHora { get; set; }
        public decimal Total { get; set; }
        public string Correlativo { get; set; }
        public string NumeroSerie { get; set; }
        public short IdSucursal { get; set; }
        public short Estado { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public byte EstadoTraslado { get; set; }
        public string TipoPago { get; set; }
        public Nullable<long> NumeroAutorizacion { get; set; }
        public string FelSerie { get; set; }
        public string FelNumero { get; set; }
        public string FelDescripcion { get; set; }
        public string FelNombre { get; set; }
        public string FelDireccion { get; set; }
        public Nullable<bool> EnviadoWs { get; set; }
        public Nullable<bool> Anulada { get; set; }
        public Nullable<long> CodigoAcceso { get; set; }
        public string Mensaje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
