//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoInventario
    {
        public long IdMovimientoInventario { get; set; }
        public long IdProducto { get; set; }
        public string NombreProducto { get; set; }
        public decimal SaldoInicial { get; set; }
        public decimal CantidadEntrada { get; set; }
        public decimal Salida { get; set; }
        public decimal Ajustes { get; set; }
        public decimal SaldoFinal { get; set; }
        public short IdSucursal { get; set; }
        public System.DateTime FechaHoraMovimiento { get; set; }
        public short IdTipoMovimiento { get; set; }
    
        public virtual TipoMovimiento TipoMovimiento { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Productos Productos1 { get; set; }
        public virtual Productos Productos2 { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Sucursal Sucursal1 { get; set; }
        public virtual Sucursal Sucursal2 { get; set; }
    }
}
