//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosRecibidos
    {
        public long IdRegistro { get; set; }
        public short IdSucursal { get; set; }
        public long IdProducto { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public double CantidadEnviada { get; set; }
        public double CantidadConfirmada { get; set; }
        public byte Estado { get; set; }
        public long IdPedido { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
