//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.ConversionesProductos = new HashSet<ConversionesProductos>();
            this.ConversionesProductos1 = new HashSet<ConversionesProductos>();
            this.DetalleBitAjusteInventario = new HashSet<DetalleBitAjusteInventario>();
            this.DetalleInventario = new HashSet<DetalleInventario>();
            this.DetalleInventario1 = new HashSet<DetalleInventario>();
            this.DetallePluAdquirido = new HashSet<DetallePluAdquirido>();
            this.PLU = new HashSet<PLU>();
            this.RecetaDet = new HashSet<RecetaDet>();
            this.PedidosRecibidos = new HashSet<PedidosRecibidos>();
        }
    
        public string NombreCompleto { get; set; }
        public byte UnidadMedida { get; set; }
        public Nullable<short> IdCategoria { get; set; }
        public decimal Precio { get; set; }
        public Nullable<byte> Tipo { get; set; }
        public long CodigoSAP { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConversionesProductos> ConversionesProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConversionesProductos> ConversionesProductos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleBitAjusteInventario> DetalleBitAjusteInventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleInventario> DetalleInventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleInventario> DetalleInventario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePluAdquirido> DetallePluAdquirido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLU> PLU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetaDet> RecetaDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosRecibidos> PedidosRecibidos { get; set; }
    }
}
