//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroSincronizacion
    {
        public System.DateTime FechaRegistro { get; set; }
        public short Operacion { get; set; }
        public short IdSucursal { get; set; }
        public long IdRegistro { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
    }
}
