//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.CajaChica = new HashSet<CajaChica>();
        }
    
        public short PIN { get; set; }
        public short IdSucursal { get; set; }
        public short IdTipoUsuario { get; set; }
        public bool Estado { get; set; }
        public string Nombre { get; set; }
        public long IdUsuario { get; set; }
        public string Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CajaChica> CajaChica { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
