//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaClientes
    {
        public Nullable<long> IdCliente { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Nombre3 { get; set; }
        public string NombreNegocio { get; set; }
        public string DirCalle1 { get; set; }
        public string DirCalle2 { get; set; }
        public string DirColonia { get; set; }
        public string DirCiudad { get; set; }
        public string DirNumeroExt { get; set; }
        public string DirNumeroInt { get; set; }
        public string DirDepartamento { get; set; }
        public string DirPais { get; set; }
        public string TelFijo { get; set; }
        public string TelMovil { get; set; }
        public string TelFax { get; set; }
        public decimal LimiteCredito { get; set; }
        public decimal SaldoCredito { get; set; }
        public string CodigoContribuyente { get; set; }
        public string CodigoTipoNegocio { get; set; }
        public string CodigoOrganizacion { get; set; }
        public string CodigoCanalDistribucion { get; set; }
        public string CodigoSector { get; set; }
        public string CodigoCondicionPago { get; set; }
        public short DiasCredito { get; set; }
        public Nullable<short> CodigoRutaVenta { get; set; }
        public string CodigoGrupoCuenta { get; set; }
        public Nullable<long> CodigoClientePrincipal { get; set; }
        public string CodigoBloqueoPedidos { get; set; }
        public string CodigoGrupoCliente { get; set; }
        public string IdFiscal1 { get; set; }
        public string IdFiscal2 { get; set; }
        public string ClasificacionIva { get; set; }
        public string ClasificacionPercepcion { get; set; }
        public string CodigoGrupoVendedores { get; set; }
        public string CodigoZonaVenta { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string CodigoRutaReparto { get; set; }
        public string CodigoListaPrecios { get; set; }
        public string CodigoGrupoPrecios { get; set; }
        public string CodigoClaseCliente { get; set; }
        public string CodigoCompatibilidad { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string DirMunicipio { get; set; }
        public string CodigoMunicipal { get; set; }
        public string GrupoImputacion { get; set; }
        public string GrupoCuentasDeudor { get; set; }
        public string Vendedor { get; set; }
        public string AsesorTecnico { get; set; }
        public string NotaRemision { get; set; }
        public string ClienteEstrategico { get; set; }
        public string CanalAtencion { get; set; }
        public string CodigoGrupoCliente3 { get; set; }
        public string CodigoGrupoCliente4 { get; set; }
        public string CodigoGrupoCliente5 { get; set; }
        public string MacroCanal { get; set; }
        public string Canal { get; set; }
        public string ExclusivoSolucion { get; set; }
        public string Categoria { get; set; }
        public string IntensidadCompetitiva { get; set; }
        public string TipoNegocio { get; set; }
        public string CorreoElectronico { get; set; }
        public Nullable<long> CodigoAgrupador { get; set; }
        public string CanalSubCanal { get; set; }
        public Nullable<bool> IdEstadoCliente { get; set; }
    }
}
