//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaPLU
    {
        public long IdPLU { get; set; }
        public long IdReceta { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public short IdCategoria { get; set; }
        public short IdSucursal { get; set; }
        public long CodigoSAP { get; set; }
        public byte IdUnidadVenta { get; set; }
        public bool IdEstado { get; set; }
        public Nullable<bool> SeDetalla { get; set; }
    }
}
