//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaSeriesFacturas
    {
        public short idSerie { get; set; }
        public string numeroSerie { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string resolucion { get; set; }
        public string datoAdicional1 { get; set; }
        public string datoAdicional2 { get; set; }
        public string datoAdicional3 { get; set; }
        public string datoAdicional4 { get; set; }
        public string datoAdicional5 { get; set; }
        public string datoAdicional6 { get; set; }
        public string datoAdicional7 { get; set; }
        public string datoAdicional8 { get; set; }
        public string datoAdicional9 { get; set; }
        public string datoAdicional10 { get; set; }
        public string datoAdicional11 { get; set; }
        public string DatoAdicional12 { get; set; }
        public long correlativo { get; set; }
        public string estado { get; set; }
        public string nit { get; set; }
        public string nombre { get; set; }
        public string tipo_documento { get; set; }
        public string moneda { get; set; }
        public Nullable<short> idSeccion { get; set; }
        public Nullable<long> numeroDel { get; set; }
        public Nullable<long> numeroAl { get; set; }
        public string SerieNC { get; set; }
        public Nullable<long> CorrelativoNC { get; set; }
        public Nullable<long> NumeroReciboCesta { get; set; }
        public Nullable<byte> idtiposerie { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<byte> idestado { get; set; }
        public string EstadoDocumento { get; set; }
        public short idSucursal { get; set; }
    }
}
