//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ComercializacionDIPEntities : DbContext
    {
        public ComercializacionDIPEntities()
            : base("name=ComercializacionDIPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BitAjusteInventario> BitAjusteInventario { get; set; }
        public virtual DbSet<CajaChica> CajaChica { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<ConversionesProductos> ConversionesProductos { get; set; }
        public virtual DbSet<DetalleBitAjusteInventario> DetalleBitAjusteInventario { get; set; }
        public virtual DbSet<DetalleFactura> DetalleFactura { get; set; }
        public virtual DbSet<DetalleInventario> DetalleInventario { get; set; }
        public virtual DbSet<DetallePluAdquirido> DetallePluAdquirido { get; set; }
        public virtual DbSet<FacturaE> FacturaE { get; set; }
        public virtual DbSet<MotivosInventario> MotivosInventario { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<RegistroInventario> RegistroInventario { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<VistaSeriesFacturas> VistaSeriesFacturas { get; set; }
        public virtual DbSet<PLU> PLUSet { get; set; }
        public virtual DbSet<RecetaDet> RecetaDet { get; set; }
        public virtual DbSet<RecetaEnc> RecetaEnc { get; set; }
        public virtual DbSet<VistaPLU> VistaPLU { get; set; }
        public virtual DbSet<VistaReceta> VistaReceta { get; set; }
        public virtual DbSet<WebServicePath> WebServicePath { get; set; }
        public virtual DbSet<RegistroSincronizacion> RegistroSincronizacion { get; set; }
        public virtual DbSet<PedidosRecibidos> PedidosRecibidos { get; set; }
    
        public virtual ObjectResult<SPObtenerProductos_Result> SPObtenerProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPObtenerProductos_Result>("SPObtenerProductos");
        }
    
        public virtual int SPUpdateCorrelativo(string numeroSerie, Nullable<int> idSucursal, Nullable<long> correlativo, Nullable<short> serie)
        {
            var numeroSerieParameter = numeroSerie != null ?
                new ObjectParameter("NumeroSerie", numeroSerie) :
                new ObjectParameter("NumeroSerie", typeof(string));
    
            var idSucursalParameter = idSucursal.HasValue ?
                new ObjectParameter("IdSucursal", idSucursal) :
                new ObjectParameter("IdSucursal", typeof(int));
    
            var correlativoParameter = correlativo.HasValue ?
                new ObjectParameter("Correlativo", correlativo) :
                new ObjectParameter("Correlativo", typeof(long));
    
            var serieParameter = serie.HasValue ?
                new ObjectParameter("Serie", serie) :
                new ObjectParameter("Serie", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPUpdateCorrelativo", numeroSerieParameter, idSucursalParameter, correlativoParameter, serieParameter);
        }
    
        public virtual int TrasladoFacturas(Nullable<System.DateTime> fecha, Nullable<int> sucursal, string user)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var sucursalParameter = sucursal.HasValue ?
                new ObjectParameter("sucursal", sucursal) :
                new ObjectParameter("sucursal", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrasladoFacturas", fechaParameter, sucursalParameter, userParameter);
        }
    
        public virtual ObjectResult<WsGetPedidosHoyJSON_Result> WsGetPedidosHoyJSON(Nullable<long> codCliente)
        {
            var codClienteParameter = codCliente.HasValue ?
                new ObjectParameter("CodCliente", codCliente) :
                new ObjectParameter("CodCliente", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WsGetPedidosHoyJSON_Result>("WsGetPedidosHoyJSON", codClienteParameter);
        }
    
        public virtual int SPInactivarCorrelativo(string numeroSerie, Nullable<int> idSucursal)
        {
            var numeroSerieParameter = numeroSerie != null ?
                new ObjectParameter("NumeroSerie", numeroSerie) :
                new ObjectParameter("NumeroSerie", typeof(string));
    
            var idSucursalParameter = idSucursal.HasValue ?
                new ObjectParameter("IdSucursal", idSucursal) :
                new ObjectParameter("IdSucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPInactivarCorrelativo", numeroSerieParameter, idSucursalParameter);
        }
    }
}
