//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    
    public partial class WsGetPedidosHoyJSON_Result1
    {
        public Nullable<long> IdPedido { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public long idproductos { get; set; }
        public short UnidadesPedido { get; set; }
        public double PesoPedido { get; set; }
        public double PrecioUnitario { get; set; }
        public Nullable<long> Numerolinea { get; set; }
        public int UnidadFacturacion { get; set; }
    }
}
